# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build AAB and upload to Google Play track from env/options"
  lane :deploy do |options|
    track = options[:track] || ENV["PLAY_TRACK"] || "internal"
    validate_only = (ENV["PLAY_VALIDATE_ONLY"] || "false").downcase == "true"

    gradle(
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: track,
      aab: "app/build/outputs/bundle/release/app-release.aab",
      validate_only: validate_only,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_metadata: true,
      skip_upload_screenshots: true,
    )
  end
end
